version: "3.8"
services:
  ocr-tts-backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./keys/service-account.json:/app/keys/service-account.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/keys/service-account.json
      - CONFIG_PATH=/app/config.yaml
    restart: unless-stopped
